# Generated by Django 4.1.7 on 2023-03-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gobi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=200)),
                ('accountholder', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='infant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('aadharno', models.CharField(max_length=200)),
                ('panno', models.CharField(max_length=200)),
                ('mobileno', models.CharField(max_length=200)),
                ('accountno', models.CharField(max_length=200)),
            ],
        ),
    ]
